version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:12.14.1'
        environment:
          NODE_ENV: circleci
      - image: circleci/postgres:9.6.2-alpine
        environment:
          POSTGRES_DB: circlecidb
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: circleci
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "api/package.json" }}
            - v1-dependencies-
      - run: cd api; npm install
      - run: cd api; npx sequelize db:migrate
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "api/package.json" }}
      - run:
          name: Tests
          command: |
            cd api;
            npm test