// Posts
export const REQ_POSTS_PENDING = 'REQ_POSTS_PENDING';
export const REQ_POSTS_SUCCESS = 'REQ_POSTS_SUCCESS';
export const REQ_POSTS_ERROR = 'REQ_POSTS_ERROR';
export const REQ_POST_PENDING = 'REQ_POST_PENDING';
export const REQ_POST_SUCCESS = 'REQ_POST_SUCCESS';
export const REQ_POST_ERROR = 'REQ_POST_ERROR';
export const ADD_POST_PENDING = 'ADD_POST_PENDING';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_ERROR = 'ADD_POST_ERROR';
export const UPDATE_POST_PENDING = 'UPDATE_POST_PENDING';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR';
export const DELETE_POST_PENDING = 'DELETE_POST_PENDING';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';